# Generated by Django 5.2.4 on 2025-08-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyConnectapp', '0003_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
