# Generated by Django 5.2.4 on 2025-08-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyConnectapp', '0005_question_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
